persistenceUnit=default
encryptPassword=true
storePasswordAsHex=true
initialPasswordForAdmin=admin

startInLastVisitedModule=true
showModulesMenuWhenNotLogged=true
#fixModulesOnTopMenu=Invoice, Order
#initialModule=Invoice
#rememberVisitedModules=false
unauthorizedModule=SignIn
initialModule=Test

createSchema=CREATE SCHEMA ${schema}
# These are by database vendor, you can add yours using the database name
# as suffix (actually the first token of connection.getMetaData().getDatabaseProductName())
createSchema.PostgreSQL=CREATE SCHEMA ${schema}

dropSchema=DROP SCHEMA ${schema} CASCADE
# These are by database vendor, you can add yours using the database name
# as suffix (actually the first token of connection.getMetaData().getDatabaseProductName())
dropSchema.MySQL=DROP SCHEMA ${schema} 

# autologinUser=admin
# autologinPassword=admin
showApplicationName=true
showOrganizationOnSignIn=true
showListOfOrganizationsOnSignIn=true

updateNaviOXTablesInOrganizationsOnStartup=true

# It must implement IValidator. The default value is org.openxava.validators.EmailValidator
#emailValidatorForSignUpClass=org.openxava.validators.EmailValidator
